name: Build
on:
  push:
    branches:
      - "master"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"
jobs:
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Run spellcheck
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go install github.com/client9/misspell/cmd/misspell@latest
          misspell -error src
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: spellcheck
    steps:
      - uses: actions/checkout@v3
      - name: Build
        uses: jenkey2011/vuepress-deploy@v1.6.1
        env:
          ACCESS_TOKEN: "x-access-token:${{ secrets.GITHUB_TOKEN }}"
          BUILD_SCRIPT: npm install && npm run build
          BUILD_DIR: docs
